src/Entity/Annonces.php
<?php

namespace App\Entity;

use App\Repository\AnnoncesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

#[ORM\Entity(repositoryClass: AnnoncesRepository::class)]
class Annonces
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    #[Gedmo\Slug(fields: ['titre'])]
    private ?string $slug = null;

    #[ORM\Column(length: 255)]
    private ?string $texte = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Gedmo\Timestampable(on:'create')]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    #[ORM\ManyToOne(inversedBy: 'annonces')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'annonces')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categories $categorie = null;

    #[ORM\Column(length: 255)]
    private ?string $marque = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ville = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $region = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pays = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $typeservice = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getTexte(): ?string
    {
        return $this->texte;
    }

    public function setTexte(string $texte): static
    {
        $this->texte = $texte;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): void
    {
        $this->user = $user;
    }

    public function getCategorie(): ?Categories
    {
        return $this->categorie;
    }

    public function setCategorie(?Categories $categorie): void
    {
        $this->categorie = $categorie;

    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): static
    {
        $this->marque = $marque;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->region;
    }

    public function setRegion(?string $region): static
    {
        $this->region = $region;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(?string $pays): static
    {
        $this->pays = $pays;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getTypeservice(): ?string
    {
        return $this->typeservice;
    }

    public function setTypeservice(?string $typeservice): static
    {
        $this->typeservice = $typeservice;

        return $this;
    }
}

src/Form/AnnonceType.php
<?php

namespace App\Form;

use App\Entity\Annonces;
use App\Entity\Categories;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class AnnonceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre', TextType::class, [
                'attr' => [
                    'class' => 'h-full-width'
                ],
                'label' => "Titre",
                'label_attr' => ['style' => 'color: #b26f66; font-weight: bold;'],
            ])
            ->add('texte', TextareaType::class, [
                'attr' => [
                    'class' => 'h-full-width'
                ],
                'label' => "Description",
                'label_attr' => ['style' => 'color:#b26f66; font-weight: bold;'],
            ])
            ->add('photo', FileType::class, [
                'label' => 'Télécharger une photo',
                'mapped' => false,
                'required' => false,
                'data_class' => null,
                'label_attr' => ['style' => 'color: #b26f66; font-weight: bold;'],
            ])
        ;
        if ($options['is_immobilier']) {
            $builder
                ->add('ville', TextType::class, [
                    'attr' => [
                        'class' => 'h-full-width'
                    ],
                    'label' => "Ville",
                    'label_attr' => ['style' => 'color: #b26f66; font-weight: bold;'],
                ])
                ->add('region', TextType::class, [
                    'attr' => [
                        'class' => 'h-full-width'
                    ],
                    'label' => "Région",
                    'label_attr' => ['style' => 'color: #b26f66; font-weight: bold;'],
                ])
                ->add('pays', CountryType::class, [
                    'attr' => [
                        'class' => 'h-full-width'
                    ],
                    'label' => "Pays",
                    'label_attr' => ['style' => 'color: #b26f66; font-weight: bold;'],
                ])
                ->add('prix', NumberType::class, [
                    'attr' => [
                        'class' => 'h-full-width'
                    ],
                    'label' => "Prix",
                    'label_attr' => ['style' => 'color: #b26f66; font-weight: bold;'],
                ])
        ;
        }
        if($options['is_vm']){
            $builder->add('marque', TextType::class, [
                'attr' => [
                    'class' => 'h-full-width',
                    'label_attr' => ['style' => 'color: #b26f66; font-weight: bold;'],
                ],
                'label' => "Marque",
                'label_attr' => ['style' => 'color: #b26f66; font-weight: bold;'],
            ])
            ->add('prix', NumberType::class, [
                'attr' => [
                    'class' => 'h-full-width'
                ],
                'label' => "Prix",
                'label_attr' => ['style' => 'color: #b26f66; font-weight: bold;'],
            ])
        ;
        }
        if($options['is_service']){
            $builder
                ->add('typeservice', TextType::class, [
                    'attr' => [
                        'class' => 'h-full-width'
                    ],
                    'label' => "Service",
                    'label_attr' => ['style' => 'color: #b26f66; font-weight: bold;'],
                ])
                ->add('prix', NumberType::class, [
                    'attr' => [
                        'class' => 'h-full-width'
                    ],
                    'label' => "Prix",
                    'label_attr' => ['style' => 'color: #b26f66; font-weight: bold;'],
                ])
        ;
        }
        if($options['is_vetements']){
            $builder
                ->add('marque', TextType::class, [
                    'attr' => [
                        'class' => 'h-full-width'
                    ],
                    'label' => "Marque",
                    'label_attr' => ['style' => 'color: #b26f66; font-weight: bold;'],
                ])
                ->add('prix', NumberType::class, [
                    'attr' => [
                        'class' => 'h-full-width'
                    ],
                    'label' => "Prix",
                    'label_attr' => ['style' => 'color: #b26f66; font-weight: bold;'],
                ])
        ;
        }
        if($options['is_mt']){
            $builder
                ->add('marque', TextType::class, [
                    'attr' => [
                        'class' => 'h-full-width'
                    ],
                    'label' => "Marque",
                    'label_attr' => ['style' => 'color: #b26f66; font-weight: bold;'],
                ])
                ->add('prix', NumberType::class, [
                    'attr' => [
                        'class' => 'h-full-width'
                    ],
                    'label' => "Prix",
                    'label_attr' => ['style' => 'color: #b26f66; font-weight: bold;'],
                ])
        ;
        }
        if($options['is_autre']){
            $builder
            ->add('typeservice', TextType::class, [
                'attr' => [
                    'class' => 'h-full-width'
                ],
                'label' => "Type",
                'label_attr' => ['style' => 'color: #b26f66; font-weight: bold;'],
                ])
                ->add('prix', NumberType::class, [
                    'attr' => [
                        'class' => 'h-full-width'
                    ],
                    'label' => "Prix",
                    'label_attr' => ['style' => 'color: #b26f66; font-weight: bold;'],
                ])
        ;
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Annonces::class,
            'is_immobilier' => false,
            'is_vm' => false,
            'is_service'=>false,
            'is_vetements'=>false,
            'is_mt'=>false,
            'is_autre'=>false,
        ]);
    }
}

src/Controller/Admin/AnnoncesController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Annonces;
use App\Repository\AnnoncesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/annonces", name="admin_annonces_")
 * @package App\Controller\Admin
 */
class AnnoncesController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(AnnoncesRepository $annoncesRepo)
    {
        return $this->render('admin/annonces/index.html.twig', [
            'annonces' => $annoncesRepo->findAll()
        ]);
    }

    /**
     * @Route("/supprimer/{id}", name="supprimer")
     */
    public function supprimer(Annonces $annonce)
    {

        if (!$this->getUser() || !$this->isGranted('ROLE_ADMIN')) {
            return $this->redirectToRoute('app_login');
        }
        
        // Get the photo filename
        $photoFilename = $annonce->getPhoto();

        // Delete the photo file from the folder
        $photoPath = $this->getParameter('kernel.project_dir') . '/public/uploads/' . $photoFilename;
        if (file_exists($photoPath)) {
            unlink($photoPath);
        }

        $em = $this->getDoctrine()->getManager();
        $em->remove($annonce);
        $em->flush();

        $this->addFlash('message', 'Annonce supprimée avec succès');
        return $this->redirectToRoute('admin_annonces_home');
    }
}

src/Controller/AnnoncesController.php
<?php

namespace App\Controller;

use App\Entity\Annonces;
use App\Entity\Categories;
use App\Form\AnnonceType;
use App\Entity\AnnonceImmobilier;
use App\Form\AnnonceImmobilierType;
use App\Repository\AnnoncesRepository;
use App\Repository\CategoriesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface;


class AnnoncesController extends AbstractController
{
    private $annoncesRepo;
    private $flashMessage;
    private $entityManager;
    
    public function __construct(AnnoncesRepository $annoncesRepo,FlashBagInterface $flashMessage,EntityManagerInterface  $entityManager){
        $this->annoncesRepo=$annoncesRepo;
        $this->flashMessage=$flashMessage;
        $this->entitymanager=$entityManager;
    }
    
    #[Route('/annonces', name: 'annonces_home')]
    public function index(AnnoncesRepository $annoncesRepo, Request $request)
    {
        $annonces = $annoncesRepo->findAll();
        return $this->render('annonces/index.html.twig',[
            "annonces" => $annonces
        ]);
    }

    #[Route('/')]
    public function home(AnnoncesRepository $annoncesRepo,CategoriesRepository $categoriesRepo)
    {
        $firstThreeAnnonces = $annoncesRepo->findRecent(3);
        $categories = $categoriesRepo->findAll();
        return $this->render('main/index.html.twig', [
            'annonces' => $firstThreeAnnonces,
            'categories' => $categories,
        ]);
    }

    #[Route('/annonces/{id}', name: 'annonces_show')]
    public function showannonce($id)
    {
        $annonces = $this->annoncesRepo->find($id);
        return $this->render('annonces/show.html.twig',[
            "annonces" => $annonces
        ]);
    }

    #[Route('/annonces/{categorie}/edit/{id}', name: 'annonces_edit')]
    public function editAnnonce(Annonces $annonce,Request $request,string $categorie ,CategoriesRepository $categoryRepo)
    {

        if (!($this->getUser())) {
            return $this->redirectToRoute('app_login');
        }
        $category = $categoryRepo->findOneBy(['nom' => $categorie]);
        $form = $this->createForm(AnnonceType::class,$annonce, [
            'is_immobilier' => ($categorie === 'Immobilier'),
            'is_vm' => ($categorie === 'Voitures & Motos'),
            'is_service' => ($categorie === 'Service'),
            'is_vetements' => ($categorie === 'Vêtements'),
            'is_mt' => ($categorie === 'Mobiles & Tablettes'),
            'is_autre' => ($categorie === 'Autre'),
        ]);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
        
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($annonce);
            $entityManager->flush();

            $this->addFlash('success', 'Annonce modifiée !');
            return $this->redirectToRoute('annonces_show', ['id' => $annonce->getId()]);
        }
            return $this->renderForm('annonces/edit.html.twig', [
                'form' => $form,
                'categorie' => $categorie,
            ]);
    }

    #[Route('/annonces/delete/{id}', name: 'annonces_delete')]
    public function deleteAnnonce(Annonces $annonce)
    {
            if (!($this->getUser())) {
                return $this->redirectToRoute('app_login');
            }
             // Get the photo filename
            $photoFilename = $annonce->getPhoto();

            // Delete the photo file from the folder
            $photoPath = $this->getParameter('kernel.project_dir') . '/public/uploads/' . $photoFilename;
            if (file_exists($photoPath)) {
                unlink($photoPath);
            }
            
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($annonce);
            $entityManager->flush();
            $this->flashMessage->add("success","Annonce supprimée !");
            return $this->redirectToRoute('annonces_home');
    }

    #[Route('/annonces/show/{categorie}', name:'app_annonce_by_category')]
    public function annoncesByCategorie(string $categorie, AnnoncesRepository $annoncesRepo)
    {
        $annonces = $annoncesRepo->findByCategorienom($categorie);
        return $this->render('annonces/annonces.html.twig', [
            'annonces' => $annonces,
            'categorie' =>  $categorie
        ]);
    }

}

templates/annonces/annonces.html.twig
{% extends "base.html.twig" %}

{% block title %}
	ANNONCES
	{{categorie|upper}}
{% endblock %}

{% block body %}

	<style>
		button {
			display: flex;
			align-items: center;
			justify-content: center;
			color: whitesmoke;
			background-color: #b26f66;
			text-decoration: none;
			font-weight: bold;
			text-align: center;
			border: 2px solid transparent;
			padding: 13px 30px;
			border-radius: 30px;
			transition: 0.4s;
		}
		button:hover {
			background-color: transparent;
			border: 2px solid #b26f66;
			cursor: pointer;
			color: #333;
		}
		.button-container {
			display: flex;
			align-items: center;
			justify-content: center;
		}
		.success-msg {
			color: #270;
			background-color: #dff0d8;
			border: 1px solid #d6e9c6;
			color: #3c763d;
			border-radius: 5px;
			padding: 10px;
			border-radius: 5px;
			width: 50%;
			margin-top: 20px;
		}
		.msg-container {
			display: flex;
			justify-content: center;
		}
	</style>
	{% if categorie != 'Autre' %}
		<h2 style="text-align:center; margin-top:1.5rem;">
			ANNONCES
			{{categorie|upper}}
		</h2>
	{% else %}
		<h2 style="text-align:center; margin-top:1.5rem;">
			ANNONCES
		</h2>
	{% endif %}
	<br>
	{% for message in app.flashes("success") %}
		<div class="msg-container">
			<div class="success-msg">
				<i class="fa fa-check"></i>
				{{ message }}
			</div>
		</div>
	{% endfor %}
	<br>
	<br>
	<section class="articles">
		{% for annonce in annonces %}
			<article>
				<div class="article-wrapper">
					<figure>
						<img src="{{ asset('/uploads/'~annonce.photo) }}" alt=""/>
					</figure>
					<div class="article-body">
						<h2>
							{{annonce.titre}}
						</h2>
						<h3>
							{{annonce.prix}}
							MAD
						</h3>
						<a href="{{path("annonces_show" , {id:annonce.id})}}" class="read-more">
							Plus de détails
							<span class="sr-only">
								about this is some title
							</span>
							<svg xmlns="http://www.w3.org/2000/svg" class="icon" viewbox="0 0 20 20" fill="currentColor">
								<path fill-rule="evenodd" d="M12.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd"/>
							</svg>
						</a>
					</div>
				</div>
			</article>
		{% endfor %}
	</section>
	<br>
	<div class="button-container">
		{% if app.user %}
			{% if "ROLE_ADMIN" not in app.user.roles %}
				<a href="{{path("user_annonces_ajout",{categorie : categorie})}}">
					<button>
						Publier une annonce
					</button>
				</a>
			{% endif %}
		{% endif %}
	</div>
{% endblock %}

templates/annonces/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}
	MODIFIER L'ANNONCE
{% endblock %}

{% block body %}
	<style>
		input[type=file]::file-selector-button {
			margin-right: 20px;
			border: none;
			background: #b26f66;
			padding: 10px 20px;
			border-radius: 10px;
			color: #fff;
			cursor: pointer;
			transition: background 0.2s ease-in-out;
		}

		input[type=file]::file-selector-button:hover {
			background-color: transparent;
			border: 2px solid #b26f66;
			cursor: pointer;
			color: #333;
		}

		.button-container {
			display: flex;
			align-items: center;
			justify-content: center;
		}

		button {
			display: flex;
			align-items: center;
			justify-content: center;
			color: whitesmoke;
			background-color: #b26f66;
			text-decoration: none;
			font-weight: bold;
			text-align: center;
			border: 2px solid transparent;
			padding: 13px 30px;
			border-radius: 30px;
			transition: 0.4s;
		}
		button:hover {
			background-color: transparent;
			border: 2px solid #b26f66;
			cursor: pointer;
			color: #333;
		}
		i {
			font-size: 50px;
			display: block;
			text-align: center;
			margin: 25px 0;
			color: #333;
		}
	</style>
	<section class="articles1">
		<h2 style="margin-top:2rem;">
			MODIFIER L'ANNONCE
		</h2>
		{{form_start(form, {'attr': { 'style': 'width: 100%;'}}
		)}}
		{{form_row(form.titre, {'attr': {'style': 'width: 100%;'}}
		)}}
		{{form_row(form.texte, {'attr': {'style': 'width: 100%;'}}
		)}}
		<div style="display: flex; justify-content: center;">
			{{form_row(form.photo,{'attr' : {'type' : 'file','style': 'width: 100%;'}}
			)}}
		</div>
		{% if categorie == 'Immobilier' %}
			{{form_row(form.ville, {'attr': {'style': 'width: 100%;'}}
			)}}
			{{form_row(form.region, {'attr': {'style': 'width: 100%;'}}
			)}}
			{{form_row(form.pays, {'attr': {'style': 'width: 100%;'}}
			)}}
			{{form_row(form.prix, {'attr': {'style': 'width: 100%;'}}
			)}}
		{% endif %}
		{% if categorie == 'Voitures & Motos' %}
			{{form_row(form.marque, {'attr': {'style': 'width: 100%;'}}
			)}}
			{{form_row(form.prix, {'attr': {'style': 'width: 100%;'}}
			)}}
		{% endif %}
		{% if categorie == 'Service' %}
			{{form_row(form.typeservice, {'attr': {'style': 'width: 100%;'}}
			)}}
			{{form_row(form.prix, {'attr': {'style': 'width: 100%;'}}
			)}}
		{% endif %}
		{% if categorie == 'Vêtements' %}
			{{form_row(form.marque, {'attr': {'style': 'width: 100%;'}}
			)}}
			{{form_row(form.prix, {'attr': {'style': 'width: 100%;'}}
			)}}
		{% endif %}
		{% if categorie == 'Mobiles & Tablettes' %}
			{{form_row(form.marque, {'attr': {'style': 'width: 100%;'}}
			)}}
			{{form_row(form.prix, {'attr': {'style': 'width: 100%;'}}
			)}}
		{% endif %}
		{% if categorie == 'Autre' %}
			{{form_row(form.typeservice, {'attr': {'style': 'width: 100%;'}}
			)}}
			{{form_row(form.prix, {'attr': {'style': 'width: 100%;'}}
			)}}
		{% endif %}
		<div class="button-container">
			<button type="submit">
				Modifier
			</button>
		</div>
		{{form_end(form)}}
	</section>
{% endblock %}

templates/annonces/index.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Annonces
{% endblock %}

{% block body %}
	<style>
		.success-msg {
			color: #270;
			background-color: #dff0d8;
			border: 1px solid #d6e9c6;
			color: #3c763d;
			border-radius: 5px;
			padding: 10px;
			border-radius: 5px;
			width: 50%;
			margin-top: 20px;
		}
		.msg-container {
			display: flex;
			justify-content: center;
		}
	</style>
	{% for message in app.flashes("success") %}
		<div class="msg-container">
			<div class="success-msg">

				<i class="fa fa-check"></i>
				{{ message }}

			</div>
		</div>
	{% endfor %}
	<br>
	<br>
	<section class="articles">
		{% for annonce in annonces %}
			<article>
				<div class="article-wrapper">
					<figure>
						<img src="{{ asset('/uploads/'~annonce.photo) }}" alt=""/>
					</figure>
					<div class="article-body">
						<h2>
							{{annonce.titre}}
						</h2>
						<a href="{{path("annonces_show" , {id:annonce.id})}}" class="read-more">
							Plus de détails
							<span class="sr-only">
								about this is some title
							</span>
							<svg xmlns="http://www.w3.org/2000/svg" class="icon" viewbox="0 0 20 20" fill="currentColor">
								<path fill-rule="evenodd" d="M12.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd"/>
							</svg>
						</a>
					</div>
				</div>
			</article>
		{% endfor %}
	</section>
{% endblock %}

templates/annonces/show.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Annonce
	{{annonces.titre}}
{% endblock %}
{% block head %}
{% endblock %}
{% block body %}

	<style>
		.button-container {
			display: flex;
			align-items: center;
			justify-content: center;
		}
		button {
			display: flex;
			align-items: center;
			justify-content: center;
			background-color: #b26f66;
			border: 2px solid transparent;
			padding: 13px 30px;
			border-radius: 30px;
			transition: 0.4s;
		}
		button i {
			color: #333;
		}
		button:hover {
			background-color: transparent;
			border: 2px solid #b26f66;
			cursor: pointer;
		}
		.success-msg {
			color: #270;
			background-color: #dff0d8;
			border: 1px solid #d6e9c6;
			color: #3c763d;
			border-radius: 5px;
			padding: 10px;
			border-radius: 5px;
			width: 50%;
			margin-top: 20px;
		}
		.msg-container {
			display: flex;
			justify-content: center;
		}
	</style>
	{% for message in app.flashes("success") %}
		<div class="msg-container">
			<div class="success-msg">
				<i class="fa fa-check"></i>
				{{ message }}
			</div>
		</div>
	{% endfor %}
	<br>
	<br>
	<section class="articles1">
		<div class="article-wrapper">
			<figure>
				<img src="{{ asset('/uploads/'~annonces.photo) }}" alt=""/>
			</figure>
			<div class="article">
				<h2>
					{{annonces.titre}}
				</h2>
				<p>
					{{annonces.texte}}
				</p>
				<h3>
					Prix :
					{{annonces.prix}}
					MAD
				</h3>
				{% if annonces.categorie == 'Service' %}
					<h3>
						Type de service :
						{{annonces.typeservice}}
					</h3>
				{% endif %}
				{% if annonces.categorie == 'Autre' %}
					<h3>
						Type :
						{{annonces.typeservice}}
					</h3>
				{% endif %}
				{% if annonces.categorie == 'Immobilier' %}
					<h3>
						Ville :
						{{annonces.ville}}
					</h3>
					<h3>
						Région :
						{{annonces.region}}
					</h3>
					<h3>
						Pays :
						{{annonces.pays}}
					</h3>
				{% endif %}
				{% if annonces.categorie == 'Voitures & Motos' %}
					<h3>
						Marque :
						{{annonces.marque}}
					</h3>
				{% endif %}
				{% if  annonces.categorie == 'Vêtements'%}
					<h3>
						Marque :
						{{annonces.marque}}
					</h3>
				{% endif %}
				{% if  annonces.categorie == 'Mobiles & Tablettes'  %}
					<h3>
						Marque :
						{{annonces.marque}}
					</h3>
				{% endif %}
				<h3>
					{{annonces.createdAt|date}}
				</h3>
				{% if is_granted('ROLE_USER') %}
					{% if annonces.user.id == app.user.id %}
						<div class="button-container">
							<a href="{{ path('annonces_edit', {'id': annonces.id, 'categorie': annonces.categorie}) }}">
								<button>
									<i class="fa fa-edit"></i>
								</button>
							</a>
							<a href="{{path("annonces_delete",{id:annonces.id})}}">
								<button>
									<i class="fa fa-trash"></i>
								</button>
							</a>
						</div>
						{% endif%}
					{% endif %}
				</div>
			</div>
		</section>

	{% endblock %}